-- 执行这些SQL，将TEXT改为MEDIUMTEXT（可存储16MB）
ALTER TABLE km_note MODIFY COLUMN core_concept MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN mechanism MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN application_case MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN extension MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN common_mistake MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN reflection MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN original_text MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN explanation MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN cue MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN question_description MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN analysis MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN reference_answer MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN requirement_description MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN design_thinking MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN reference_design MEDIUMTEXT;
ALTER TABLE km_note MODIFY COLUMN content MEDIUMTEXT;