-- 创建笔记归档表
CREATE TABLE IF NOT EXISTS `note_archive` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ARCHIVE_NAME` VARCHAR(200) NOT NULL COMMENT '归档名称（如：材料名称、书籍名称）',
  `ARCHIVE_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '归档类型（如：book-书籍,course-课程,material-材料,video-视频,other-其他）',
  `DESCRIPTION` TEXT COMMENT '归档描述',
  `SOURCE_INFO` VARCHAR(500) DEFAULT NULL COMMENT '来源信息（如：作者、出版社、链接等）',
  `NOTE_COUNT` INT(11) DEFAULT 0 COMMENT '包含笔记数量',
  `REC_CREATOR` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `REC_CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `REC_REVISOR` VARCHAR(64) DEFAULT NULL COMMENT '修改人',
  `REC_REVISE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ARCH_FLAG` TINYINT(1) DEFAULT 0 COMMENT '归档标志:0-未归档,1-已归档',
  PRIMARY KEY (`ID`),
  KEY `IDX_ARCHIVE_NAME` (`ARCHIVE_NAME`),
  KEY `IDX_ARCHIVE_TYPE` (`ARCHIVE_TYPE`),
  KEY `IDX_CREATE_TIME` (`REC_CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记归档表';

-- 创建笔记归档关联表（多对多关系）
CREATE TABLE IF NOT EXISTS `note_archive_relation` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ARCHIVE_ID` BIGINT(20) NOT NULL COMMENT '归档ID',
  `NOTE_ID` BIGINT(20) NOT NULL COMMENT '笔记ID',
  `RELATION_NOTE` VARCHAR(500) DEFAULT NULL COMMENT '关联备注（如：章节、页码等）',
  `REC_CREATOR` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `REC_CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `REC_REVISOR` VARCHAR(64) DEFAULT NULL COMMENT '修改人',
  `REC_REVISE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ARCH_FLAG` TINYINT(1) DEFAULT 0 COMMENT '归档标志:0-未归档,1-已归档',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_ARCHIVE_NOTE` (`ARCHIVE_ID`, `NOTE_ID`),
  KEY `IDX_ARCHIVE_ID` (`ARCHIVE_ID`),
  KEY `IDX_NOTE_ID` (`NOTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记归档关联表';

